spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/user?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000
      use-key-prefix: true
      key-prefix: cache
    cache-names: user